### ISSUE TITLE
Running csv_to_json.py raises error: "TypeError: string indices must be integers"

### ISSUE THREAD

**Issue by harryytsao** [ZetangForward/Detox-CoT#1]
python csv_to_json.py --input ../dataset/train.csv --json_save ../dataset/train.json --span_json_save ../span_cnn_train.json
Traceback (most recent call last):
  File "csv_to_json.py", line 76, in <module>
    if lst[i]['toxic'] == '0':
TypeError: string indices must be integerst

**Comment by jiqimaoke** [comment]
The issue is that the variable lst[i] has not been converted into a dictionary format. We have uploaded a revised version to the repository. This version includes minor adjustments to the folder structure for improved readability. We recommend re-downloading the repository to access these updates.
